version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - API_URL='https://workout-app-951785297505.us-east1.run.app'
    command: [ "node", "dist/server.js" ]
