version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3000
      - GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback
    command: [ "node", "dist/server.js" ]
